In [1]:
import pandas as pd

In [2]:
# Series single column of data.
# Dataframe

import pandas as pd
array1 = [1,9,10,11]
series1 = pd.Series(array1)
display(series1)
print(type(series1))

0     1
1     9
2    10
3    11
dtype: int64

<class 'pandas.core.series.Series'>

In [2]:
series1.index

RangeIndex(start=0, stop=4, step=1)

In [3]:
calories = {"Day1":320, "Day2":500, "Day3":700, "Day4":900}
series2 = pd.Series(calories)
display(series2)

Day1    320
Day2    500
Day3    700
Day4    900
dtype: int64

# Data Frames

In [4]:
data ={
    "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "Calories": [100,200,300,400,500,600,700],
    "Gym": [True, False, False, False, True, True, True]
}
df = pd.DataFrame(data)
display(df)

        days  Calories    Gym
0     Monday       100   True
1    Tuesday       200  False
2  Wednesday       300  False
3   Thursday       400  False
4     Friday       500   True
5   Saturday       600   True
6     Sunday       700   True

In [5]:
df.loc[3:6]

       days  Calories    Gym
3  Thursday       400  False
4    Friday       500   True
5  Saturday       600   True
6    Sunday       700   True

In [6]:
df.loc[4]

days        Friday
Calories       500
Gym           True
Name: 4, dtype: object

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.shape

(7, 3)

In [9]:
list(df.columns)

['days', 'Calories', 'Gym']

In [10]:
list(df.index )

[0, 1, 2, 3, 4, 5, 6]

In [11]:
list(df.values)

[array(['Monday', 100, True], dtype=object),
 array(['Tuesday', 200, False], dtype=object),
 array(['Wednesday', 300, False], dtype=object),
 array(['Thursday', 400, False], dtype=object),
 array(['Friday', 500, True], dtype=object),
 array(['Saturday', 600, True], dtype=object),
 array(['Sunday', 700, True], dtype=object)]

In [12]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [13]:
df.loc # to Locate

In [14]:
df.iloc[3:6,0:2] #

       days  Calories
3  Thursday       400
4    Friday       500
5  Saturday       600

In [18]:
pandas1 = [method for method in dir(pd) if not method.startswith('__')] # Pandas Method
for function, method in enumerate(pandas1):
    print(f'{function+1}. {method}')

1. ArrowDtype
2. BooleanDtype
3. Categorical
4. CategoricalDtype
5. CategoricalIndex
6. DataFrame
7. DateOffset
8. DatetimeIndex
9. DatetimeTZDtype
10. ExcelFile
11. ExcelWriter
12. Flags
13. Float32Dtype
14. Float64Dtype
15. Grouper
16. HDFStore
17. Index
18. IndexSlice
19. Int16Dtype
20. Int32Dtype
21. Int64Dtype
22. Int8Dtype
23. Interval
24. IntervalDtype
25. IntervalIndex
26. MultiIndex
27. NA
28. NaT
29. NamedAgg
30. Period
31. PeriodDtype
32. PeriodIndex
33. RangeIndex
34. Series
35. SparseDtype
36. StringDtype
37. Timedelta
38. TimedeltaIndex
39. Timestamp
40. UInt16Dtype
41. UInt32Dtype
42. UInt64Dtype
43. UInt8Dtype
44. _built_with_meson
45. _config
46. _is_numpy_dev
47. _libs
48. _pandas_datetime_CAPI
49. _pandas_parser_CAPI
50. _testing
51. _typing
52. _version_meson
53. annotations
54. api
55. array
56. arrays
57. bdate_range
58. compat
59. concat
60. core
61. crosstab
62. cut
63. date_range
64. describe_option
65. errors
66. eval
67. factorize
68. from_dummies
69. get_dummies
70. get_option
71. infer_freq
72. interval_range
73. io
74. isna
75. isnull
76. json_normalize
77. lreshape
78. melt
79. merge
80. merge_asof
81. merge_ordered
82. notna
83. notnull
84. offsets
85. option_context
86. options
87. pandas
88. period_range
89. pivot
90. pivot_table
91. plotting
92. qcut
93. read_clipboard
94. read_csv
95. read_excel
96. read_feather
97. read_fwf
98. read_gbq
99. read_hdf
100. read_html
101. read_json
102. read_orc
103. read_parquet
104. read_pickle
105. read_sas
106. read_spss
107. read_sql
108. read_sql_query
109. read_sql_table
110. read_stata
111. read_table
112. read_xml
113. reset_option
114. set_eng_float_format
115. set_option
116. show_versions
117. test
118. testing
119. timedelta_range
120. to_datetime
121. to_numeric
122. to_pickle
123. to_timedelta
124. tseries
125. unique
126. util
127. value_counts
128. wide_to_long

In [15]:
dataframes = [method for method in dir(df) if not method.startswith('__')]  # Data Frames Mehtods
for function, method in enumerate(dataframes):
    print(f'{function+1}. {method}')

1. Calories
2. Gym
3. T
4. _AXIS_LEN
5. _AXIS_ORDERS
6. _AXIS_TO_AXIS_NUMBER
7. _HANDLED_TYPES
8. _accessors
9. _accum_func
10. _agg_examples_doc
11. _agg_see_also_doc
12. _align_for_op
13. _align_frame
14. _align_series
15. _append
16. _arith_method
17. _arith_method_with_reindex
18. _as_manager
19. _attrs
20. _box_col_values
21. _can_fast_transpose
22. _check_inplace_and_allows_duplicate_labels
23. _check_is_chained_assignment_possible
24. _check_label_or_level_ambiguity
25. _check_setitem_copy
26. _clear_item_cache
27. _clip_with_one_bound
28. _clip_with_scalar
29. _cmp_method
30. _combine_frame
31. _consolidate
32. _consolidate_inplace
33. _construct_axes_dict
34. _construct_result
35. _constructor
36. _constructor_from_mgr
37. _constructor_sliced
38. _constructor_sliced_from_mgr
39. _create_data_for_split_and_tight_to_dict
40. _data
41. _deprecate_downcast
42. _dir_additions
43. _dir_deletions
44. _dispatch_frame_op
45. _drop_axis
46. _drop_labels_or_levels
47. _ensure_valid_index
48. _find_valid_index
49. _flags
50. _flex_arith_method
51. _flex_cmp_method
52. _from_arrays
53. _from_mgr
54. _get_agg_axis
55. _get_axis
56. _get_axis_name
57. _get_axis_number
58. _get_axis_resolvers
59. _get_block_manager_axis
60. _get_bool_data
61. _get_cleaned_column_resolvers
62. _get_column_array
63. _get_index_resolvers
64. _get_item_cache
65. _get_label_or_level_values
66. _get_numeric_data
67. _get_value
68. _get_values_for_csv
69. _getitem_bool_array
70. _getitem_multilevel
71. _getitem_nocopy
72. _getitem_slice
73. _gotitem
74. _hidden_attrs
75. _indexed_same
76. _info_axis
77. _info_axis_name
78. _info_axis_number
79. _info_repr
80. _init_mgr
81. _inplace_method
82. _internal_names
83. _internal_names_set
84. _is_copy
85. _is_homogeneous_type
86. _is_label_or_level_reference
87. _is_label_reference
88. _is_level_reference
89. _is_mixed_type
90. _is_view
91. _is_view_after_cow_rules
92. _iset_item
93. _iset_item_mgr
94. _iset_not_inplace
95. _item_cache
96. _iter_column_arrays
97. _ixs
98. _logical_func
99. _logical_method
100. _maybe_align_series_as_frame
101. _maybe_cache_changed
102. _maybe_update_cacher
103. _metadata
104. _mgr
105. _min_count_stat_function
106. _needs_reindex_multi
107. _pad_or_backfill
108. _protect_consolidate
109. _reduce
110. _reduce_axis1
111. _reindex_axes
112. _reindex_multi
113. _reindex_with_indexers
114. _rename
115. _replace_columnwise
116. _repr_data_resource_
117. _repr_fits_horizontal_
118. _repr_fits_vertical_
119. _repr_html_
120. _repr_latex_
121. _reset_cache
122. _reset_cacher
123. _sanitize_column
124. _series
125. _set_axis
126. _set_axis_name
127. _set_axis_nocheck
128. _set_is_copy
129. _set_item
130. _set_item_frame_value
131. _set_item_mgr
132. _set_value
133. _setitem_array
134. _setitem_frame
135. _setitem_slice
136. _shift_with_freq
137. _should_reindex_frame_op
138. _slice
139. _stat_function
140. _stat_function_ddof
141. _take_with_is_copy
142. _to_dict_of_blocks
143. _to_latex_via_styler
144. _typ
145. _update_inplace
146. _validate_dtype
147. _values
148. _where
149. abs
150. add
151. add_prefix
152. add_suffix
153. agg
154. aggregate
155. align
156. all
157. any
158. apply
159. applymap
160. asfreq
161. asof
162. assign
163. astype
164. at
165. at_time
166. attrs
167. axes
168. backfill
169. between_time
170. bfill
171. bool
172. boxplot
173. clip
174. columns
175. combine
176. combine_first
177. compare
178. convert_dtypes
179. copy
180. corr
181. corrwith
182. count
183. cov
184. cummax
185. cummin
186. cumprod
187. cumsum
188. days
189. describe
190. diff
191. div
192. divide
193. dot
194. drop
195. drop_duplicates
196. droplevel
197. dropna
198. dtypes
199. duplicated
200. empty
201. eq
202. equals
203. eval
204. ewm
205. expanding
206. explode
207. ffill
208. fillna
209. filter
210. first
211. first_valid_index
212. flags
213. floordiv
214. from_dict
215. from_records
216. ge
217. get
218. groupby
219. gt
220. head
221. hist
222. iat
223. idxmax
224. idxmin
225. iloc
226. index
227. infer_objects
228. info
229. insert
230. interpolate
231. isetitem
232. isin
233. isna
234. isnull
235. items
236. iterrows
237. itertuples
238. join
239. keys
240. kurt
241. kurtosis
242. last
243. last_valid_index
244. le
245. loc
246. lt
247. map
248. mask
249. max
250. mean
251. median
252. melt
253. memory_usage
254. merge
255. min
256. mod
257. mode
258. mul
259. multiply
260. ndim
261. ne
262. nlargest
263. notna
264. notnull
265. nsmallest
266. nunique
267. pad
268. pct_change
269. pipe
270. pivot
271. pivot_table
272. plot
273. pop
274. pow
275. prod
276. product
277. quantile
278. query
279. radd
280. rank
281. rdiv
282. reindex
283. reindex_like
284. rename
285. rename_axis
286. reorder_levels
287. replace
288. resample
289. reset_index
290. rfloordiv
291. rmod
292. rmul
293. rolling
294. round
295. rpow
296. rsub
297. rtruediv
298. sample
299. select_dtypes
300. sem
301. set_axis
302. set_flags
303. set_index
304. shape
305. shift
306. size
307. skew
308. sort_index
309. sort_values
310. squeeze
311. stack
312. std
313. style
314. sub
315. subtract
316. sum
317. swapaxes
318. swaplevel
319. tail
320. take
321. to_clipboard
322. to_csv
323. to_dict
324. to_excel
325. to_feather
326. to_gbq
327. to_hdf
328. to_html
329. to_json
330. to_latex
331. to_markdown
332. to_numpy
333. to_orc
334. to_parquet
335. to_period
336. to_pickle
337. to_records
338. to_sql
339. to_stata
340. to_string
341. to_timestamp
342. to_xarray
343. to_xml
344. transform
345. transpose
346. truediv
347. truncate
348. tz_convert
349. tz_localize
350. unstack
351. update
352. value_counts
353. values
354. var
355. where
356. xs

In [19]:
pd.read_csv

<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'>

In [3]:
import pandas as pd
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.shape

(891, 12)

In [28]:
df.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [6]:
df.Age.mean()

29.69911764705882

In [5]:
df["Fare_class"]  = df.Fare/df.Pclass

In [4]:
df ["Fare_class"] = ""
for i in df.index:
  if df.loc[i, "Fare"] > 70:
    df.loc[i,"Fare_class"]= "elite"
  elif df.loc[i, "Fare"] > 30 and df.loc[i,"Fare"] < 69:
    df.loc[i,"Fare_class"]= "Avergae"
  else:
    df.loc[i,"Fare_class"]= "Basic"

In [7]:
for col in df.columns:
    print(f"\nColumn: {col}")
df[col]

Column: PassengerId

Column: Survived

Column: Pclass

Column: Name

Column: Sex

Column: Age

Column: SibSp

Column: Parch

Column: Ticket

Column: Fare

Column: Cabin

Column: Embarked

Column: Fare_class

0       2.416667
1      71.283300
2       2.641667
3      53.100000
4       2.683333
         ...
886     6.500000
887    30.000000
888     7.816667
889    30.000000
890     2.583333
Name: Fare_class, Length: 891, dtype: float64

In [8]:
df.Name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# prompt: draw a file column wise

import pandas as pd

# Assuming your data is in a CSV file named 'your_file.csv'
# Replace 'your_file.csv' with the actual filename if different
try:
    df = pd.read_csv('your_file.csv')
except FileNotFoundError:
    print("Error: 'your_file.csv' not found. Please ensure the file exists in the current directory or provide the correct path.")
    exit()


# Display each column individually
for col in df.columns:
    print(f"\nColumn: {col}")
df[col]

In [ ]:
# Data Aggregation
# Group By , reduces the Data/sums it up

In [9]:
survival_rate = df.groupby("Survived")

In [14]:
survival_rate = df.groupby(["Survived"])["Fare"].sum().reset_index()
survival_rate

   Survived        Fare
0         0  12142.7199
1         1  16551.2294

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Fare_class   891 non-null    float64
dtypes: float64(3), int64(5), object(5)
memory usage: 90.6+ KB